// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternative_text: dynamic(() => import("./AlternativeText")),
  bigtext: dynamic(() => import("./Bigtext")),
  caurosel: dynamic(() => import("./Caurosel")),
  dive: dynamic(() => import("./Dive")),
  hero: dynamic(() => import("./Hero")),
};
